### ISSUE TITLE
Please include build command for docker compose

### ISSUE THREAD

**Issue by JohnnyPh** [callbacked/noip-autorenew-gui#1]
Please include build command for docker compose, autorenew gui is supper useful for beginner like me, but I don't know where to start. Thank you!

**Comment by callbacked** [comment]
Hello, [just added instructions to run the program using ``docker run``](https://github.com/callbacked/noip-autorenew-gui#running), was trying to figure out how to publish the image to Docker Hub. All is good now!

**Comment by JohnnyPh** [comment]
Nice work, it would be much better if you can publish your build to Unraid Community App. In this community, an docker app with good effort could gain a million to half a billion download…
https://forums.unraid.net/topic/87144-ca-application-policies-notes/
